[package]
name = "advent-of-code-2024-in-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.11.1"
itertools = "0.13.0"
rayon = "1.10.0"
image = "0.25.5"
imageproc = "0.23"
rusttype = "0.9"
bitvec = "1.0.1"